from collections import defaultdict

pronouns = {
    'anyone': ['singular', 'genderless'],
    'anything': ['singular', 'genderless'],
    'everyone': ['singular', 'genderless'],
    'everything': ['singular', 'genderless'],
    'he': ['singular', 'masculine'],
    'her': ['singular', 'feminine'],
    'herself': ['singular', 'feminine'],
    'him': ['singular', 'masculine'],
    'himself': ['singular', 'masculine'],
    'i': ['singular', 'genderless'],
    'it': ['singular', 'genderless'],
    'itself': ['singular', 'genderless'],
    'me': ['singular', 'genderless'],
    'mine': ['singular', 'genderless'],
    'my': ['singular', 'genderless'],
    'myself': ['singular', 'genderless'],
    'nothing': ['singular', 'genderless'],
    'one': ['singular', 'genderless'],
    'our': ['plural', 'genderless'],
    'ours': ['plural', 'genderless'],
    'ourselves': ['plural', 'genderless'],
    'she': ['singular', 'feminine'],
    'somebody': ['singular', 'genderless'],
    'someone': ['singular', 'genderless'],
    'something': ['singular', 'genderless'],
    'that': ['singular', 'genderless'],
    'that': ['singular', 'genderless'],
    'their': ['plural', 'genderless'],
    'theirs': ['plural', 'genderless'],
    'them': ['plural', 'genderless'],
    'themselves': ['plural', 'genderless'],
    'they': ['plural', 'genderless'],
    'us': ['plural', 'genderless'],
    'we': ['plural', 'genderless'],
    'whatever': ['singular', 'genderless'],
    'whatsoever': ['singular', 'genderless'],
    'when': ['singular', 'genderless'],
    'which': ['singular', 'genderless'],
    'whichever': ['singular', 'genderless'],
    'whichsoever': ['singular', 'genderless'],
    'who': ['singular', 'genderless'],
    'whoever': ['singular', 'genderless'],
    'whom': ['singular', 'genderless'],
    'whomever': ['singular', 'genderless'],
    'whomsoever': ['singular', 'genderless'],
    'whose': ['singular', 'genderless'],
    'whosesoever': ['singular', 'genderless'],
    'whosoever': ['singular', 'genderless'],
    'you': ['singular', 'genderless'],
    'your': ['singular', 'genderless'],
    'yours': ['singular', 'genderless'],
    'yourself': ['singular', 'genderless'],
    'yourselves': ['plural', 'genderless'],
}

masculine_words = [
    'male',
    'boy',
    'man',
    'guy',
    'brother',
    'father',
    'uncle',
    'paternal',
    'macho',
    'masculine'
],

feminine_words = [
    'female',
    'girl',
    'woman',
    'lady',
    'sister',
    'mother',
    'aunt',
    'maternal',
    'feminine'
]